[2025-09-23T00:07:48.530+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-23T00:07:48.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_iceberg_pipeline.process_taxi_data scheduled__2025-09-22T00:00:00+00:00 [queued]>
[2025-09-23T00:07:48.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_iceberg_pipeline.process_taxi_data scheduled__2025-09-22T00:00:00+00:00 [queued]>
[2025-09-23T00:07:48.579+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-23T00:07:48.593+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): process_taxi_data> on 2025-09-22 00:00:00+00:00
[2025-09-23T00:07:48.601+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_iceberg_pipeline', 'process_taxi_data', 'scheduled__2025-09-22T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/spark_iceberg_pipeline.py', '--cfg-path', '/tmp/tmp4s9ik2xd']
[2025-09-23T00:07:48.603+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask process_taxi_data
[2025-09-23T00:07:48.606+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=271) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-23T00:07:48.606+0000] {standard_task_runner.py:64} INFO - Started process 273 to run task
[2025-09-23T00:07:48.676+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_iceberg_pipeline.process_taxi_data scheduled__2025-09-22T00:00:00+00:00 [running]> on host bff560919a81
[2025-09-23T00:07:48.840+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_iceberg_pipeline' AIRFLOW_CTX_TASK_ID='process_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-22T00:00:00+00:00'
[2025-09-23T00:07:48.841+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-23T00:07:48.913+0000] {spark_submit.py:304} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-09-23T00:07:48.917+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.77.1,software.amazon.awssdk:bundle:2.24.8 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1 --conf spark.sql.catalog.nessie.ref=main --conf spark.sql.catalog.nessie.authentication.type=NONE --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog --conf spark.sql.catalog.nessie.s3.endpoint=http://minio:9000 --conf spark.sql.catalog.nessie.warehouse=s3://gold/ --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name arrow-spark --verbose /opt/***/jobs/process_taxi_data.py
[2025-09-23T00:07:49.067+0000] {spark_submit.py:649} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-09-23T00:07:49.068+0000] {spark_submit.py:649} INFO - JAVA_HOME is not set
[2025-09-23T00:07:49.071+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-23T00:07:49.081+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.77.1,software.amazon.awssdk:bundle:2.24.8 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1 --conf spark.sql.catalog.nessie.ref=main --conf spark.sql.catalog.nessie.authentication.type=NONE --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog --conf spark.sql.catalog.nessie.s3.endpoint=http://minio:9000 --conf spark.sql.catalog.nessie.warehouse=s3://gold/ --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name arrow-spark --verbose /opt/***/jobs/process_taxi_data.py. Error code is: 1.
[2025-09-23T00:07:49.085+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_iceberg_pipeline, task_id=process_taxi_data, run_id=scheduled__2025-09-22T00:00:00+00:00, execution_date=20250922T000000, start_date=20250923T000748, end_date=20250923T000749
[2025-09-23T00:07:49.094+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task process_taxi_data (Cannot execute: spark-submit --master yarn --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.77.1,software.amazon.awssdk:bundle:2.24.8 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1 --conf spark.sql.catalog.nessie.ref=main --conf spark.sql.catalog.nessie.authentication.type=NONE --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog --conf spark.sql.catalog.nessie.s3.endpoint=http://minio:9000 --conf spark.sql.catalog.nessie.warehouse=s3://gold/ --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name arrow-spark --verbose /opt/***/jobs/process_taxi_data.py. Error code is: 1.; 273)
[2025-09-23T00:07:49.104+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-23T00:07:49.120+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T00:07:49.122+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
