[2025-09-23T03:09:20.538+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-23T03:09:20.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_iceberg_pipeline.process_taxi_data manual__2025-09-23T03:04:15.737325+00:00 [queued]>
[2025-09-23T03:09:20.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_iceberg_pipeline.process_taxi_data manual__2025-09-23T03:04:15.737325+00:00 [queued]>
[2025-09-23T03:09:20.572+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-23T03:09:20.582+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): process_taxi_data> on 2025-09-23 03:04:15.737325+00:00
[2025-09-23T03:09:20.589+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_iceberg_pipeline', 'process_taxi_data', 'manual__2025-09-23T03:04:15.737325+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/spark_iceberg_pipeline.py', '--cfg-path', '/tmp/tmp661hckz3']
[2025-09-23T03:09:20.591+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask process_taxi_data
[2025-09-23T03:09:20.591+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-23T03:09:20.592+0000] {standard_task_runner.py:64} INFO - Started process 486 to run task
[2025-09-23T03:09:20.629+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_iceberg_pipeline.process_taxi_data manual__2025-09-23T03:04:15.737325+00:00 [running]> on host 211eee646d06
[2025-09-23T03:09:20.696+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_iceberg_pipeline' AIRFLOW_CTX_TASK_ID='process_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T03:04:15.737325+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-23T03:04:15.737325+00:00'
[2025-09-23T03:09:20.696+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-23T03:09:20.707+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-09-23T03:09:20.709+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.77.1,software.amazon.awssdk:bundle:2.24.8 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1 --conf spark.sql.catalog.nessie.ref=main --conf spark.sql.catalog.nessie.authentication.type=NONE --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog --conf spark.sql.catalog.nessie.s3.endpoint=http://minio:9000 --conf spark.sql.catalog.nessie.warehouse=s3://gold/ --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name arrow-spark --verbose /opt/***/jobs/process_taxi_data.py
[2025-09-23T03:09:20.813+0000] {spark_submit.py:649} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /opt/bitnami/java/bin/java: No such file or directory
[2025-09-23T03:09:20.814+0000] {spark_submit.py:649} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-09-23T03:09:20.821+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-23T03:09:20.838+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.77.1,software.amazon.awssdk:bundle:2.24.8 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1 --conf spark.sql.catalog.nessie.ref=main --conf spark.sql.catalog.nessie.authentication.type=NONE --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog --conf spark.sql.catalog.nessie.s3.endpoint=http://minio:9000 --conf spark.sql.catalog.nessie.warehouse=s3://gold/ --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name arrow-spark --verbose /opt/***/jobs/process_taxi_data.py. Error code is: 1.
[2025-09-23T03:09:20.844+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_iceberg_pipeline, task_id=process_taxi_data, run_id=manual__2025-09-23T03:04:15.737325+00:00, execution_date=20250923T030415, start_date=20250923T030920, end_date=20250923T030920
[2025-09-23T03:09:20.855+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task process_taxi_data (Cannot execute: spark-submit --master spark-master:7077 --conf spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.77.1,software.amazon.awssdk:bundle:2.24.8 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions --conf spark.sql.catalog.nessie=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.nessie.uri=http://nessie:19120/api/v1 --conf spark.sql.catalog.nessie.ref=main --conf spark.sql.catalog.nessie.authentication.type=NONE --conf spark.sql.catalog.nessie.catalog-impl=org.apache.iceberg.nessie.NessieCatalog --conf spark.sql.catalog.nessie.s3.endpoint=http://minio:9000 --conf spark.sql.catalog.nessie.warehouse=s3://gold/ --conf spark.sql.catalog.nessie.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --name arrow-spark --verbose /opt/***/jobs/process_taxi_data.py. Error code is: 1.; 486)
[2025-09-23T03:09:20.886+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-23T03:09:20.906+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T03:09:20.909+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
